apiVersion: v1
kind: Pod
metadata:
  name: lables
  namespace: roboshop
  labels:
    project: roboshop
    name: lables
    environment: dev
    purpose: learning
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80